### ISSUE TITLE
The demo is not working

### ISSUE THREAD

**Issue by Stefdv** [gundb/onward#2]
The demo gives errors.

"ReferenceError: Gun is not defined
    at http://null.jsbin.com/runner:4:14
    at https://static.jsbin.com/js/prod/runner-3.39.15.min.js:1:10979"

**Comment by amark** [comment]
Hmm, I just ran the demo and it worked? Did you happen to be offline while running it or something, cause it looks like Gun didn't even get loaded for you (it should).

**Comment by Stefdv** [comment]
Oeps...i'm sorry...don't know what happened..but yes..it is working...my bad. Closing issue
