### ISSUE TITLE
onward is the victim of the 'leaking' problem

### ISSUE THREAD

**Issue by Stefdv** [gundb/onward#4]
Gun.onward will kill your data unless you add 
```
....
Gun.obj.map(change, function(val, field){
      change = Gun.obj.copy(change)  // otherwise it will kill your data
....
```

**Comment by Stefdv** [comment]
I also notice you (@amark  ) use `this.path(field)` ? But `gun/lib/path` is not required ?

**Comment by amark** [comment]
@Stefdv thanks, does your PR fix this?

**Comment by Stefdv** [comment]
Changes are merged tx @amark 
Closing issue
